修复调整
2468785842/ImsTech pull request #7
Opened 2024-11-02 03:36 UTC by KingPrimes

#5

2024-11-02 03:38 UTC, KingPrimes reviewed
// 采用ID定位
            const t = (await tLoc
                .locator(`#learning-activity-${course.activityId}`)
                .getByText(course.activityName, {exact: true})
                .elementHandle())!;

2024-11-03 12:12 UTC, 2468785842 commented on src/index.ts
> +                        i + 1,
这里索引需要+1

2024-11-03 12:12 UTC, 2468785842 requested changes
请调整代码缩进为 2 个空格以符合项目的代码风格

2024-11-03 12:14 UTC, 2468785842 commented on src/course/processor/MaterialProc.ts
> +      new Promise(resolve => setTimeout(resolve,1500))
请使用, page.waitForTime而不是自己写promise,而且这里并没有await

2024-11-03 12:16 UTC, 2468785842 commented on src/course/processor/OnlineVideoProc.ts
> +    }*/
这里是有加载失败的状况的, 不应该删除

2024-11-03 12:17 UTC, 2468785842 commented on src/index.ts
> +          await Sleep(1500)
可以使用import { sleep } from 'openai/core.js';
而不是自己实现

2024-11-03 12:20 UTC, 2468785842 commented on src/utils.ts
> +export const Sleep = (ms: number) => {
使用OpenAi库提供的sleep: import { sleep } from 'openai/core.js';

2024-11-03 12:21 UTC, 2468785842 requested changes
请调整代码缩进为 2 个空格以符合项目的代码风格, 修改内容

2024-11-03 13:03 UTC, 2468785842 commented on src/index.ts
> -                if (await es.$('xpath=../*[contains(@class, "upcoming")]')) {
$方法被标记为过时

2024-11-04 02:10 UTC, 2468785842 commented on src/index.ts
> +                    await sleep(1500)
这里能用page.waitForTimeout还是优先使用, 为什么要等待1.5秒?

2024-11-04 02:13 UTC, 2468785842 commented
我添加了个[.prettierrc](https://github.com/2468785842/ImsTech/blob/master/.prettierrc)配置文件
你添加项目根目录使用prettier格式化一下, 因为项目使用的都是单引号
使用插件或者安装 prettier 
npx prettier --write ./src

2024-11-09 18:14 UTC, closed without merging